// Generated by scripts/gen_db_types.py from the production catalog
// (project giodrtaddvmkgvmzomxv). Do not edit by hand; rerun the script after a migration.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type NbActivityDir = "outbound" | "inbound" | "internal";
export type NbActivityKind = "visit" | "call" | "text" | "email_out" | "email_in" | "linkedin" | "newsletter" | "meeting" | "note" | "order" | "sample_drop" | "staff_training" | "field_note";
export type NbDataOrigin = "synthetic" | "hubspot" | "excel_import" | "manual" | "enriched";
export type NbDealStage = "identified" | "contacted" | "discovery" | "sampled" | "trial" | "stocked" | "reordered" | "closed_won" | "closed_lost";
export type NbScoreKind = "fit" | "engagement" | "potential";
export type NbSdrKind = "call" | "visit";

export type NbAccountBriefsRow = {
  account_id: string;
  summary_md: string | null;
  specializes_in: string[] | null;
  review_sentiment: Json | null;
  decision_maker_note: string | null;
  machine_md: string | null;
  human_md: string | null;
  sources: Json;
  refreshed_at: string | null;
  stale_after: string;
  origin: NbDataOrigin;
  synthetic_dataset_id: string | null;
  updated_at: string;
};
export type NbAccountBriefsInsert = {
  account_id: string;
  summary_md?: string | null;
  specializes_in?: string[] | null;
  review_sentiment?: Json | null;
  decision_maker_note?: string | null;
  machine_md?: string | null;
  human_md?: string | null;
  sources?: Json;
  refreshed_at?: string | null;
  stale_after?: string;
  origin: NbDataOrigin;
  synthetic_dataset_id?: string | null;
  updated_at?: string;
};

export type NbAccountEventsRow = {
  id: number;
  account_id: string;
  at: string;
  actor: string | null;
  event: string;
  detail: string | null;
  meta: Json | null;
};
export type NbAccountEventsInsert = {
  id?: number;
  account_id: string;
  at?: string;
  actor?: string | null;
  event: string;
  detail?: string | null;
  meta?: Json | null;
};

export type NbAccountScoresRow = {
  id: number;
  account_id: string;
  kind: NbScoreKind;
  value: number;
  confidence: number;
  inputs: Json;
  inputs_known: number;
  inputs_total: number;
  config_version: string;
  computed_at: string;
  computed_by: string;
  origin: NbDataOrigin;
  synthetic_dataset_id: string | null;
};
export type NbAccountScoresInsert = {
  id?: number;
  account_id: string;
  kind: NbScoreKind;
  value: number;
  confidence: number;
  inputs: Json;
  inputs_known?: number;
  inputs_total?: number;
  config_version: string;
  computed_at?: string;
  computed_by?: string;
  origin: NbDataOrigin;
  synthetic_dataset_id?: string | null;
};

export type NbAccountsRow = {
  id: string;
  name: string;
  dba: string | null;
  channel: string;
  street: string | null;
  city: string | null;
  state: string | null;
  postal: string | null;
  lat: number | null;
  lng: number | null;
  geo: unknown | null;
  phone: string | null;
  website: string | null;
  hubspot_company_id: string | null;
  lifecycle: string;
  first_order_at: string | null;
  last_order_at: string | null;
  lifetime_revenue: number | null;
  trailing_12m_revenue: number | null;
  expected_reorder_days: number | null;
  expected_reorder_at: string | null;
  business_hours: Json | null;
  timezone: string;
  quirks: string | null;
  current_state: string | null;
  future_state: string | null;
  impact: string | null;
  do_not_visit: boolean;
  enrichment_status: Json;
  dirty_fields: Json;
  origin: NbDataOrigin;
  synthetic_dataset_id: string | null;
  created_at: string;
  updated_at: string;
  email: string | null;
  instagram_url: string | null;
  facebook_url: string | null;
  linkedin_url: string | null;
  erp_customer_code: string | null;
  erp_customer_type: string | null;
  retail_mode: string | null;
  store_type: string | null;
  locations_count: number | null;
  employees_est: number | null;
  annual_revenue_usd: number | null;
  has_online_shop: boolean | null;
  has_private_label: boolean | null;
  is_family_owned: boolean | null;
  part_of_group: boolean | null;
  group_name: string | null;
  places_id: string | null;
  places_primary_type: string | null;
  places_types: string[] | null;
  places_rating: number | null;
  places_rating_count: number | null;
  places_status: string | null;
  potential_hq: string | null;
  alternates: Json;
  hubspot_owner_id: string | null;
  owner_name: string | null;
  area: string | null;
  chain_excluded: boolean;
  chain_excluded_at: string | null;
  practice_excluded: boolean;
  practice_excluded_at: string | null;
  closed_at: string | null;
  closed_reason: string | null;
  lead_status: string | null;
  potential_juan: string | null;
  hubspot_sync_eligible: boolean;
  source: string | null;
  source_external_id: string | null;
  source_pulled_at: string | null;
  readiness: string | null;
  readiness_set_at: string | null;
  shelf_units: number | null;
  supp_body_pct: number | null;
  employee_count: number | null;
  stores_per_decision_maker: number | null;
  tier_synced: string | null;
};
export type NbAccountsInsert = {
  id: string;
  name: string;
  dba?: string | null;
  channel?: string;
  street?: string | null;
  city?: string | null;
  state?: string | null;
  postal?: string | null;
  lat?: number | null;
  lng?: number | null;
  phone?: string | null;
  website?: string | null;
  hubspot_company_id?: string | null;
  lifecycle?: string;
  first_order_at?: string | null;
  last_order_at?: string | null;
  lifetime_revenue?: number | null;
  trailing_12m_revenue?: number | null;
  expected_reorder_days?: number | null;
  expected_reorder_at?: string | null;
  business_hours?: Json | null;
  timezone?: string;
  quirks?: string | null;
  current_state?: string | null;
  future_state?: string | null;
  impact?: string | null;
  do_not_visit?: boolean;
  enrichment_status?: Json;
  dirty_fields?: Json;
  origin: NbDataOrigin;
  synthetic_dataset_id?: string | null;
  created_at?: string;
  updated_at?: string;
  email?: string | null;
  instagram_url?: string | null;
  facebook_url?: string | null;
  linkedin_url?: string | null;
  erp_customer_code?: string | null;
  erp_customer_type?: string | null;
  retail_mode?: string | null;
  store_type?: string | null;
  locations_count?: number | null;
  employees_est?: number | null;
  annual_revenue_usd?: number | null;
  has_online_shop?: boolean | null;
  has_private_label?: boolean | null;
  is_family_owned?: boolean | null;
  part_of_group?: boolean | null;
  group_name?: string | null;
  places_id?: string | null;
  places_primary_type?: string | null;
  places_types?: string[] | null;
  places_rating?: number | null;
  places_rating_count?: number | null;
  places_status?: string | null;
  potential_hq?: string | null;
  alternates?: Json;
  hubspot_owner_id?: string | null;
  owner_name?: string | null;
  area?: string | null;
  chain_excluded?: boolean;
  chain_excluded_at?: string | null;
  practice_excluded?: boolean;
  practice_excluded_at?: string | null;
  closed_at?: string | null;
  closed_reason?: string | null;
  lead_status?: string | null;
  potential_juan?: string | null;
  hubspot_sync_eligible?: boolean;
  source?: string | null;
  source_external_id?: string | null;
  source_pulled_at?: string | null;
  readiness?: string | null;
  readiness_set_at?: string | null;
  shelf_units?: number | null;
  supp_body_pct?: number | null;
  employee_count?: number | null;
  stores_per_decision_maker?: number | null;
  tier_synced?: string | null;
};

export type NbActivitiesRow = {
  id: number;
  account_id: string;
  contact_id: string | null;
  at: string;
  logged_at: string;
  kind: NbActivityKind;
  direction: NbActivityDir;
  actor: string;
  outcome: string | null;
  detail: string | null;
  route_stop_id: string | null;
  hubspot_engagement_id: string | null;
  origin: NbDataOrigin;
  synthetic_dataset_id: string | null;
};
export type NbActivitiesInsert = {
  id?: number;
  account_id: string;
  contact_id?: string | null;
  at?: string;
  logged_at?: string;
  kind: NbActivityKind;
  direction: NbActivityDir;
  actor?: string;
  outcome?: string | null;
  detail?: string | null;
  route_stop_id?: string | null;
  hubspot_engagement_id?: string | null;
  origin: NbDataOrigin;
  synthetic_dataset_id?: string | null;
};

export type NbActivityCorrectionsRow = {
  activity_id: number;
  original_kind: NbActivityKind;
  corrected_kind: NbActivityKind;
  reason: string;
  corrected_at: string;
  corrected_by: string;
};
export type NbActivityCorrectionsInsert = {
  activity_id: number;
  original_kind: NbActivityKind;
  corrected_kind: NbActivityKind;
  reason: string;
  corrected_at?: string;
  corrected_by?: string;
};

export type NbActivityRetractionsRow = {
  activity_id: number;
  duplicate_of: number | null;
  reason: string;
  retracted_at: string;
  retracted_by: string;
  archived_engagement_id: string | null;
};
export type NbActivityRetractionsInsert = {
  activity_id: number;
  duplicate_of?: number | null;
  reason: string;
  retracted_at?: string;
  retracted_by?: string;
  archived_engagement_id?: string | null;
};

export type NbAppErrorsRow = {
  fingerprint: string;
  kind: string;
  route: string;
  message: string;
  top_frame: string;
  sample_stack: string;
  count: number;
  first_seen: string;
  last_seen: string;
  rep_id: string | null;
  commit_sha: string | null;
  status: string;
  triaged_count: number;
  fix_branch: string | null;
  fix_url: string | null;
  updated_at: string;
};
export type NbAppErrorsInsert = {
  fingerprint: string;
  kind: string;
  route?: string;
  message: string;
  top_frame?: string;
  sample_stack?: string;
  count?: number;
  first_seen?: string;
  last_seen?: string;
  rep_id?: string | null;
  commit_sha?: string | null;
  status?: string;
  triaged_count?: number;
  fix_branch?: string | null;
  fix_url?: string | null;
  updated_at?: string;
};

export type NbCalendarProposalsRow = {
  id: string;
  touchpoint_id: string | null;
  account_id: string | null;
  kind: string;
  title: string;
  starts_at: string | null;
  duration_minutes: number;
  notes: string | null;
  status: string;
  gcal_event_id: string | null;
  origin: NbDataOrigin;
  created_at: string;
  decided_at: string | null;
};
export type NbCalendarProposalsInsert = {
  id: string;
  touchpoint_id?: string | null;
  account_id?: string | null;
  kind: string;
  title: string;
  starts_at?: string | null;
  duration_minutes?: number;
  notes?: string | null;
  status?: string;
  gcal_event_id?: string | null;
  origin?: NbDataOrigin;
  created_at?: string;
  decided_at?: string | null;
};

export type NbCloseSignalsRow = {
  id: string;
  account_id: string;
  activity_id: number | null;
  evidence: string;
  status: string;
  applied_at: string | null;
  dismissed_reason: string | null;
  created_at: string;
};
export type NbCloseSignalsInsert = {
  id: string;
  account_id: string;
  activity_id?: number | null;
  evidence: string;
  status?: string;
  applied_at?: string | null;
  dismissed_reason?: string | null;
  created_at?: string;
};

export type NbConfigRow = {
  key: string;
  value: Json;
  source: string;
  content_hash: string;
  published_at: string;
};
export type NbConfigInsert = {
  key: string;
  value: Json;
  source: string;
  content_hash: string;
  published_at?: string;
};

export type NbContactsRow = {
  id: string;
  account_id: string;
  hubspot_contact_id: string | null;
  first_name: string | null;
  last_name: string | null;
  title: string | null;
  role_tag: string | null;
  is_decision_maker: boolean;
  email: string | null;
  phone: string | null;
  linkedin_url: string | null;
  enrichment_status: Json;
  dirty_fields: Json;
  origin: NbDataOrigin;
  synthetic_dataset_id: string | null;
  created_at: string;
  updated_at: string;
  alternates: Json;
};
export type NbContactsInsert = {
  id: string;
  account_id: string;
  hubspot_contact_id?: string | null;
  first_name?: string | null;
  last_name?: string | null;
  title?: string | null;
  role_tag?: string | null;
  is_decision_maker?: boolean;
  email?: string | null;
  phone?: string | null;
  linkedin_url?: string | null;
  enrichment_status?: Json;
  dirty_fields?: Json;
  origin: NbDataOrigin;
  synthetic_dataset_id?: string | null;
  created_at?: string;
  updated_at?: string;
  alternates?: Json;
};

export type NbContentFlagsRow = {
  account_id: string;
  day: string;
  wants_content: boolean;
  note: string | null;
  created_at: string;
  updated_at: string;
};
export type NbContentFlagsInsert = {
  account_id: string;
  day: string;
  wants_content?: boolean;
  note?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type NbDealStageEventsRow = {
  id: number;
  deal_id: string;
  at: string;
  actor: string;
  from_stage: NbDealStage | null;
  to_stage: NbDealStage;
  evidence_activity_id: number | null;
  evidence_note: string;
  criterion_key: string | null;
};
export type NbDealStageEventsInsert = {
  id?: number;
  deal_id: string;
  at?: string;
  actor?: string;
  from_stage?: NbDealStage | null;
  to_stage: NbDealStage;
  evidence_activity_id?: number | null;
  evidence_note: string;
  criterion_key?: string | null;
};

export type NbDealsRow = {
  id: string;
  account_id: string;
  contact_id: string | null;
  stage: NbDealStage;
  amount_cents: number | null;
  expected_close: string | null;
  next_step: string | null;
  next_step_date: string | null;
  hubspot_deal_id: string | null;
  lost_reason: string | null;
  origin: NbDataOrigin;
  synthetic_dataset_id: string | null;
  created_at: string;
  updated_at: string;
};
export type NbDealsInsert = {
  id: string;
  account_id: string;
  contact_id?: string | null;
  stage?: NbDealStage;
  amount_cents?: number | null;
  expected_close?: string | null;
  next_step?: string | null;
  next_step_date?: string | null;
  hubspot_deal_id?: string | null;
  lost_reason?: string | null;
  origin: NbDataOrigin;
  synthetic_dataset_id?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type NbDevicesRow = {
  id: string;
  label: string;
  user_agent: string | null;
  created_at: string;
  last_seen_at: string | null;
  revoked_at: string | null;
  user_id: string;
};
export type NbDevicesInsert = {
  id: string;
  label: string;
  user_agent?: string | null;
  created_at?: string;
  last_seen_at?: string | null;
  revoked_at?: string | null;
  user_id?: string;
};

export type NbDirectivesRow = {
  id: string;
  field_note_id: string | null;
  directive: string;
  target: string | null;
  scope: string;
  account_id: string | null;
  status: string;
  resolution: string | null;
  created_at: string;
  decided_at: string | null;
};
export type NbDirectivesInsert = {
  id: string;
  field_note_id?: string | null;
  directive: string;
  target?: string | null;
  scope?: string;
  account_id?: string | null;
  status?: string;
  resolution?: string | null;
  created_at?: string;
  decided_at?: string | null;
};

export type NbEmailPollLogRow = {
  id: number;
  message_id: string;
  sent_at: string;
  direction: string;
  to_addresses: string[];
  matched_account_id: string | null;
  matched_contact_id: string | null;
  activity_id: number | null;
  hubspot_note_id: string | null;
  status: string;
  error: string | null;
  at: string;
};
export type NbEmailPollLogInsert = {
  id?: number;
  message_id: string;
  sent_at: string;
  direction: string;
  to_addresses?: string[];
  matched_account_id?: string | null;
  matched_contact_id?: string | null;
  activity_id?: number | null;
  hubspot_note_id?: string | null;
  status: string;
  error?: string | null;
  at?: string;
};

export type NbFieldNotesRow = {
  id: string;
  account_id: string | null;
  touchpoint_id: string | null;
  activity_id: number | null;
  at: string;
  detail: string;
  raw_text: string | null;
  topic: string;
  origin: NbDataOrigin;
  created_at: string;
};
export type NbFieldNotesInsert = {
  id: string;
  account_id?: string | null;
  touchpoint_id?: string | null;
  activity_id?: number | null;
  at?: string;
  detail: string;
  raw_text?: string | null;
  topic?: string;
  origin?: NbDataOrigin;
  created_at?: string;
};

export type NbHubspotAssociationsRow = {
  from_type: string;
  from_id: string;
  to_type: string;
  to_id: string;
  label: string | null;
  fetched_at: string;
};
export type NbHubspotAssociationsInsert = {
  from_type: string;
  from_id: string;
  to_type: string;
  to_id: string;
  label?: string | null;
  fetched_at?: string;
};

export type NbHubspotObjectMapRow = {
  entity: string;
  local_id: string;
  hubspot_id: string;
  hubspot_type: string;
  status: string;
  last_pulled_at: string | null;
  last_pushed_at: string | null;
  remote_updated_at: string | null;
  remote_hash: string | null;
};
export type NbHubspotObjectMapInsert = {
  entity: string;
  local_id: string;
  hubspot_id: string;
  hubspot_type: string;
  status?: string;
  last_pulled_at?: string | null;
  last_pushed_at?: string | null;
  remote_updated_at?: string | null;
  remote_hash?: string | null;
};

export type NbHubspotSyncLogRow = {
  id: number;
  at: string;
  direction: string;
  entity: string;
  local_id: string | null;
  hubspot_id: string | null;
  operation: string;
  payload_hash: string;
  status: string;
  http_status: number | null;
  request: Json | null;
  response: Json | null;
  error: string | null;
  job_id: string | null;
};
export type NbHubspotSyncLogInsert = {
  id?: number;
  at?: string;
  direction: string;
  entity: string;
  local_id?: string | null;
  hubspot_id?: string | null;
  operation: string;
  payload_hash: string;
  status: string;
  http_status?: number | null;
  request?: Json | null;
  response?: Json | null;
  error?: string | null;
  job_id?: string | null;
};

export type NbIdempotencyKeysRow = {
  id: string;
  response: Json;
  created_at: string;
};
export type NbIdempotencyKeysInsert = {
  id: string;
  response: Json;
  created_at?: string;
};

export type NbImportBatchesRow = {
  id: string;
  source: string;
  filename: string | null;
  row_count: number | null;
  loaded_at: string;
  note: string | null;
};
export type NbImportBatchesInsert = {
  id: string;
  source: string;
  filename?: string | null;
  row_count?: number | null;
  loaded_at?: string;
  note?: string | null;
};

export type NbImportRowsRow = {
  id: number;
  batch_id: string;
  raw: Json;
  norm_name: string | null;
  norm_phone: string | null;
  norm_street_no: string | null;
  norm_postal: string | null;
  match_account_id: string | null;
  match_score: number | null;
  match_basis: Json | null;
  decision: string;
  decided_at: string | null;
  decided_by: string | null;
  applied_account_id: string | null;
  applied_contact_id: string | null;
  applied_at: string | null;
  applied_note: string | null;
};
export type NbImportRowsInsert = {
  id?: number;
  batch_id: string;
  raw: Json;
  norm_name?: string | null;
  norm_phone?: string | null;
  norm_street_no?: string | null;
  norm_postal?: string | null;
  match_account_id?: string | null;
  match_score?: number | null;
  match_basis?: Json | null;
  decision?: string;
  decided_at?: string | null;
  decided_by?: string | null;
  applied_account_id?: string | null;
  applied_contact_id?: string | null;
  applied_at?: string | null;
  applied_note?: string | null;
};

export type NbJobsRow = {
  id: string;
  worker: string;
  target_id: string | null;
  status: string;
  requested_at: string;
  started_at: string | null;
  ended_at: string | null;
  attempt: number;
  summary: string | null;
  payload: Json | null;
  depends_on: string | null;
};
export type NbJobsInsert = {
  id?: string;
  worker: string;
  target_id?: string | null;
  status?: string;
  requested_at?: string;
  started_at?: string | null;
  ended_at?: string | null;
  attempt?: number;
  summary?: string | null;
  payload?: Json | null;
  depends_on?: string | null;
};

export type NbMatrixItemsRow = {
  id: string;
  text: string;
  description: string | null;
  quadrant: string;
  effort: number | null;
  yield_score: number | null;
  done: boolean;
  done_at: string | null;
  source: string;
  created_at: string;
  updated_at: string;
};
export type NbMatrixItemsInsert = {
  id?: string;
  text: string;
  description?: string | null;
  quadrant: string;
  effort?: number | null;
  yield_score?: number | null;
  done?: boolean;
  done_at?: string | null;
  source?: string;
  created_at?: string;
  updated_at?: string;
};

export type NbOrderEmailsRow = {
  id: number;
  account_id: string | null;
  account_name: string;
  sent_at: string;
  subject: string | null;
  line_items: Json;
  total_revenue: number;
  captured_by: string;
  captured_at: string;
  message_id: string | null;
  no_charge: boolean;
  order_fingerprint: string | null;
  source: string | null;
};
export type NbOrderEmailsInsert = {
  id?: number;
  account_id?: string | null;
  account_name: string;
  sent_at: string;
  subject?: string | null;
  line_items: Json;
  total_revenue: number;
  captured_by?: string;
  captured_at?: string;
  message_id?: string | null;
  no_charge?: boolean;
  order_fingerprint?: string | null;
  source?: string | null;
};

export type NbOrderLinesRow = {
  id: string;
  order_id: string;
  account_id: string;
  part_code: string | null;
  product_name: string | null;
  general_category: string | null;
  cate_name: string | null;
  qty: number | null;
  unit_price: number | null;
  line_revenue_cents: number;
  origin: NbDataOrigin;
  synthetic_dataset_id: string | null;
  created_at: string;
};
export type NbOrderLinesInsert = {
  id: string;
  order_id: string;
  account_id: string;
  part_code?: string | null;
  product_name?: string | null;
  general_category?: string | null;
  cate_name?: string | null;
  qty?: number | null;
  unit_price?: number | null;
  line_revenue_cents: number;
  origin: NbDataOrigin;
  synthetic_dataset_id?: string | null;
  created_at?: string;
};

export type NbOrdersRow = {
  id: string;
  account_id: string;
  deal_id: string | null;
  activity_id: number | null;
  ordered_at: string;
  order_type: string;
  revenue_cents: number;
  units: number | null;
  sell_through_pct: number | null;
  sell_through_at: string | null;
  revenue_source: string;
  external_ref: string | null;
  origin: NbDataOrigin;
  synthetic_dataset_id: string | null;
  created_at: string;
};
export type NbOrdersInsert = {
  id: string;
  account_id: string;
  deal_id?: string | null;
  activity_id?: number | null;
  ordered_at: string;
  order_type: string;
  revenue_cents: number;
  units?: number | null;
  sell_through_pct?: number | null;
  sell_through_at?: string | null;
  revenue_source: string;
  external_ref?: string | null;
  origin: NbDataOrigin;
  synthetic_dataset_id?: string | null;
  created_at?: string;
};

export type NbOutboundDraftsRow = {
  id: string;
  account_id: string | null;
  contact_id: string | null;
  channel: string;
  subject: string | null;
  body_md: string;
  play_key: string | null;
  campaign_id: string | null;
  status: string;
  approved_at: string | null;
  sent_at: string | null;
  send_error: string | null;
  provider_msg_id: string | null;
  origin: NbDataOrigin;
  synthetic_dataset_id: string | null;
  created_at: string;
  to_email: string | null;
  to_name: string | null;
  urgency: number | null;
  urgency_reason: string | null;
  urgency_set_at: string | null;
  preferred_channel: string | null;
  source_directive_id: string | null;
  callback_on: string | null;
  bcc_email: string | null;
  source_ask: string | null;
};
export type NbOutboundDraftsInsert = {
  id: string;
  account_id?: string | null;
  contact_id?: string | null;
  channel: string;
  subject?: string | null;
  body_md: string;
  play_key?: string | null;
  campaign_id?: string | null;
  status?: string;
  approved_at?: string | null;
  sent_at?: string | null;
  send_error?: string | null;
  provider_msg_id?: string | null;
  origin: NbDataOrigin;
  synthetic_dataset_id?: string | null;
  created_at?: string;
  to_email?: string | null;
  to_name?: string | null;
  urgency?: number | null;
  urgency_reason?: string | null;
  urgency_set_at?: string | null;
  preferred_channel?: string | null;
  source_directive_id?: string | null;
  callback_on?: string | null;
  bcc_email?: string | null;
  source_ask?: string | null;
};

export type NbPinAttemptsRow = {
  key: string;
  failures: number;
  window_start: string;
  locked_until: string | null;
  updated_at: string;
};
export type NbPinAttemptsInsert = {
  key: string;
  failures?: number;
  window_start?: string;
  locked_until?: string | null;
  updated_at?: string;
};

export type NbPromoCodesRow = {
  code_norm: string;
  display_code: string;
  template_id: string | null;
  client_name: string | null;
  client_company: string | null;
  snapshot: Json;
  show_margin: boolean;
  bonus_label: string | null;
  bonus_expires_at: string | null;
  expires_at: string;
  state: string;
  rep_notes: string | null;
  first_viewed_at: string | null;
  requested_at: string | null;
  created_at: string;
};
export type NbPromoCodesInsert = {
  code_norm: string;
  display_code: string;
  template_id?: string | null;
  client_name?: string | null;
  client_company?: string | null;
  snapshot: Json;
  show_margin?: boolean;
  bonus_label?: string | null;
  bonus_expires_at?: string | null;
  expires_at: string;
  state?: string;
  rep_notes?: string | null;
  first_viewed_at?: string | null;
  requested_at?: string | null;
  created_at?: string;
};

export type NbPromoOrdersRow = {
  id: string;
  code_norm: string;
  contact_name: string | null;
  contact_email: string | null;
  contact_phone: string | null;
  company: string | null;
  ship_address: Json | null;
  line_items: Json;
  totals: Json | null;
  notes: string | null;
  state: string;
  created_at: string;
  relayed_at: string | null;
};
export type NbPromoOrdersInsert = {
  id: string;
  code_norm: string;
  contact_name?: string | null;
  contact_email?: string | null;
  contact_phone?: string | null;
  company?: string | null;
  ship_address?: Json | null;
  line_items?: Json;
  totals?: Json | null;
  notes?: string | null;
  state?: string;
  created_at?: string;
  relayed_at?: string | null;
};

export type NbPromoProductsRow = {
  id: string;
  sku: string;
  name: string;
  line: string | null;
  size: string | null;
  retail_price: number | null;
  wholesale_price: number | null;
  case_pack: number | null;
  upc: string | null;
  image_url: string | null;
  active: boolean;
  created_at: string;
};
export type NbPromoProductsInsert = {
  id: string;
  sku: string;
  name: string;
  line?: string | null;
  size?: string | null;
  retail_price?: number | null;
  wholesale_price?: number | null;
  case_pack?: number | null;
  upc?: string | null;
  image_url?: string | null;
  active?: boolean;
  created_at?: string;
};

export type NbPromoTemplatesRow = {
  id: string;
  name: string;
  client_type: string;
  headline: string | null;
  subhead: string | null;
  body_blocks: Json;
  show_margin: boolean;
  bonus_label: string | null;
  is_general: boolean;
  active: boolean;
  version: number;
  created_at: string;
  updated_at: string;
};
export type NbPromoTemplatesInsert = {
  id: string;
  name: string;
  client_type: string;
  headline?: string | null;
  subhead?: string | null;
  body_blocks?: Json;
  show_margin?: boolean;
  bonus_label?: string | null;
  is_general?: boolean;
  active?: boolean;
  version?: number;
  created_at?: string;
  updated_at?: string;
};

export type NbReportDraftsRow = {
  report_date: string;
  kind: string;
  payload: Json | null;
  status: string;
  dirty: boolean;
  preview_path: string | null;
  decided_at: string | null;
  sent_at: string | null;
  send_error: string | null;
  created_at: string;
  updated_at: string;
  rebuild_requested: boolean;
  edited: boolean;
  user_id: string;
};
export type NbReportDraftsInsert = {
  report_date: string;
  kind?: string;
  payload?: Json | null;
  status?: string;
  dirty?: boolean;
  preview_path?: string | null;
  decided_at?: string | null;
  sent_at?: string | null;
  send_error?: string | null;
  created_at?: string;
  updated_at?: string;
  rebuild_requested?: boolean;
  edited?: boolean;
  user_id?: string;
};

export type NbReportMetricsRow = {
  report_date: string;
  metric: string;
  value: number;
  updated_at: string;
  user_id: string;
};
export type NbReportMetricsInsert = {
  report_date: string;
  metric: string;
  value?: number;
  updated_at?: string;
  user_id?: string;
};

export type NbRouteDaysRow = {
  id: string;
  plan_id: string;
  date: string;
  kind: string;
  depart_at: string | null;
  return_by: string | null;
  start_lat: number | null;
  start_lng: number | null;
  cluster_id: string | null;
  prospect_block_start: string | null;
  prospect_block_end: string | null;
  status: string;
  directions_cache: Json | null;
};
export type NbRouteDaysInsert = {
  id: string;
  plan_id: string;
  date: string;
  kind?: string;
  depart_at?: string | null;
  return_by?: string | null;
  start_lat?: number | null;
  start_lng?: number | null;
  cluster_id?: string | null;
  prospect_block_start?: string | null;
  prospect_block_end?: string | null;
  status?: string;
  directions_cache?: Json | null;
};

export type NbRoutePlanRevisionsRow = {
  id: number;
  plan_id: string;
  day_id: string | null;
  at: string;
  actor: string;
  reason: string;
  diff: Json;
};
export type NbRoutePlanRevisionsInsert = {
  id?: number;
  plan_id: string;
  day_id?: string | null;
  at?: string;
  actor: string;
  reason: string;
  diff: Json;
};

export type NbRoutePlansRow = {
  id: string;
  week_start: string;
  status: string;
  planned_at: string | null;
  committed_at: string | null;
  config: Json | null;
  origin: NbDataOrigin;
  synthetic_dataset_id: string | null;
  created_at: string;
};
export type NbRoutePlansInsert = {
  id: string;
  week_start: string;
  status?: string;
  planned_at?: string | null;
  committed_at?: string | null;
  config?: Json | null;
  origin: NbDataOrigin;
  synthetic_dataset_id?: string | null;
  created_at?: string;
};

export type NbRouteStopsRow = {
  id: string;
  day_id: string;
  account_id: string;
  seq: number;
  pinned: boolean;
  locked_time: string | null;
  priority_score: number;
  priority_band: number;
  window_open: string | null;
  window_close: string | null;
  eta: string | null;
  etd: string | null;
  drive_seconds: number | null;
  drive_meters: number | null;
  dwell_minutes: number;
  status: string;
  outcome_activity_id: number | null;
};
export type NbRouteStopsInsert = {
  id: string;
  day_id: string;
  account_id: string;
  seq: number;
  pinned?: boolean;
  locked_time?: string | null;
  priority_score: number;
  priority_band: number;
  window_open?: string | null;
  window_close?: string | null;
  eta?: string | null;
  etd?: string | null;
  drive_seconds?: number | null;
  drive_meters?: number | null;
  dwell_minutes?: number;
  status?: string;
  outcome_activity_id?: number | null;
};

export type NbSampleDropsRow = {
  id: number;
  sample_id: string;
  account_id: string;
  activity_id: number | null;
  qty: number;
  at: string;
  converted_order_id: string | null;
};
export type NbSampleDropsInsert = {
  id?: number;
  sample_id: string;
  account_id: string;
  activity_id?: number | null;
  qty?: number;
  at?: string;
  converted_order_id?: string | null;
};

export type NbSamplesRow = {
  id: string;
  sku: string;
  product_name: string;
  on_hand: number;
  reorder_threshold: number;
  updated_at: string;
  origin: NbDataOrigin;
  synthetic_dataset_id: string | null;
};
export type NbSamplesInsert = {
  id: string;
  sku: string;
  product_name: string;
  on_hand?: number;
  reorder_threshold?: number;
  updated_at?: string;
  origin: NbDataOrigin;
  synthetic_dataset_id?: string | null;
};

export type NbScoreConfigProposalsRow = {
  id: string;
  from_version: string | null;
  weights: Json;
  rationale: string;
  backtest: Json | null;
  status: string;
  created_at: string;
  approved_at: string | null;
};
export type NbScoreConfigProposalsInsert = {
  id?: string;
  from_version?: string | null;
  weights: Json;
  rationale: string;
  backtest?: Json | null;
  status?: string;
  created_at?: string;
  approved_at?: string | null;
};

export type NbScoreConfigsRow = {
  version: string;
  weights: Json;
  note: string | null;
  applied_at: string;
  applied_by: string;
};
export type NbScoreConfigsInsert = {
  version: string;
  weights: Json;
  note?: string | null;
  applied_at?: string;
  applied_by?: string;
};

export type NbSdrScheduleRow = {
  id: string;
  account_id: string | null;
  prospect_name: string | null;
  prospect_phone: string | null;
  kind: NbSdrKind;
  scheduled_date: string;
  status: string;
  notes: string | null;
  completed_activity_id: number | null;
  origin: NbDataOrigin;
  created_at: string;
  rescheduled_at: string | null;
  priority: string | null;
};
export type NbSdrScheduleInsert = {
  id: string;
  account_id?: string | null;
  prospect_name?: string | null;
  prospect_phone?: string | null;
  kind?: NbSdrKind;
  scheduled_date: string;
  status?: string;
  notes?: string | null;
  completed_activity_id?: number | null;
  origin?: NbDataOrigin;
  created_at?: string;
  rescheduled_at?: string | null;
  priority?: string | null;
};

export type NbSearchJobsRow = {
  id: string;
  stage: string;
  params: Json;
  status: string;
  result: Json | null;
  error: string | null;
  created_at: string;
  started_at: string | null;
  updated_at: string;
};
export type NbSearchJobsInsert = {
  id: string;
  stage: string;
  params: Json;
  status?: string;
  result?: Json | null;
  error?: string | null;
  created_at?: string;
  started_at?: string | null;
  updated_at?: string;
};

export type NbSupportIssuesRow = {
  id: string;
  account_id: string;
  contact_id: string | null;
  raised_at: string;
  issue_type: string;
  summary: string;
  status: string;
  forwarded_at: string | null;
  forwarded_to: string | null;
  forward_msg_id: string | null;
  hq_ref: string | null;
  origin: NbDataOrigin;
  synthetic_dataset_id: string | null;
  created_at: string;
  updated_at: string;
};
export type NbSupportIssuesInsert = {
  id: string;
  account_id: string;
  contact_id?: string | null;
  raised_at?: string;
  issue_type: string;
  summary: string;
  status?: string;
  forwarded_at?: string | null;
  forwarded_to?: string | null;
  forward_msg_id?: string | null;
  hq_ref?: string | null;
  origin: NbDataOrigin;
  synthetic_dataset_id?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type NbSyncConflictsRow = {
  id: string;
  entity: string;
  local_id: string;
  property: string;
  local_value: string | null;
  remote_value: string | null;
  local_changed_at: string | null;
  remote_changed_at: string | null;
  detected_at: string;
  resolution: string | null;
  resolved_at: string | null;
  resolved_by: string | null;
};
export type NbSyncConflictsInsert = {
  id?: string;
  entity: string;
  local_id: string;
  property: string;
  local_value?: string | null;
  remote_value?: string | null;
  local_changed_at?: string | null;
  remote_changed_at?: string | null;
  detected_at?: string;
  resolution?: string | null;
  resolved_at?: string | null;
  resolved_by?: string | null;
};

export type NbSyntheticDatasetsRow = {
  id: string;
  label: string;
  note: string;
  created_at: string;
  purged_at: string | null;
};
export type NbSyntheticDatasetsInsert = {
  id: string;
  label: string;
  note: string;
  created_at?: string;
  purged_at?: string | null;
};

export type NbTerritoryAreasRow = {
  id: string;
  label: string;
  color: string;
  display_order: number;
  named_by_human: boolean;
  needs_review: boolean;
  brief: string | null;
  account_count: number;
  boundary: Json | null;
  updated_at: string;
};
export type NbTerritoryAreasInsert = {
  id: string;
  label: string;
  color: string;
  display_order?: number;
  named_by_human?: boolean;
  needs_review?: boolean;
  brief?: string | null;
  account_count?: number;
  boundary?: Json | null;
  updated_at?: string;
};

export type NbTouchpointsRow = {
  id: string;
  account_id: string | null;
  raw_text: string;
  status: string;
  account_match_confidence: string | null;
  activity_id: number | null;
  parsed: Json | null;
  origin: NbDataOrigin;
  created_at: string;
  attachments: Json;
};
export type NbTouchpointsInsert = {
  id: string;
  account_id?: string | null;
  raw_text: string;
  status?: string;
  account_match_confidence?: string | null;
  activity_id?: number | null;
  parsed?: Json | null;
  origin?: NbDataOrigin;
  created_at?: string;
  attachments?: Json;
};

export type NbTrafficCorridorsRow = {
  id: string;
  name: string;
  path: unknown | null;
  penalty: Json;
  note: string | null;
};
export type NbTrafficCorridorsInsert = {
  id: string;
  name: string;
  path?: unknown | null;
  penalty: Json;
  note?: string | null;
};

export type NbUiPrefsRow = {
  id: number;
  show_chain_accounts: boolean;
  updated_at: string;
  show_practice_accounts: boolean;
  route_draft: Json;
  route_depart: string;
  route_dwell_minutes: number;
  route_lunch_minutes: number;
  route_start: Json | null;
  route_end: Json | null;
  route_calls: Json;
  route_done: Json;
  route_mileage: Json;
  last_location: Json;
  last_route_odo: Json;
  route_stop_times: Json;
  show_prospect_accounts: boolean;
};
export type NbUiPrefsInsert = {
  id?: number;
  show_chain_accounts?: boolean;
  updated_at?: string;
  show_practice_accounts?: boolean;
  route_draft?: Json;
  route_depart?: string;
  route_dwell_minutes?: number;
  route_lunch_minutes?: number;
  route_start?: Json | null;
  route_end?: Json | null;
  route_calls?: Json;
  route_done?: Json;
  route_mileage?: Json;
  last_location?: Json;
  last_route_odo?: Json;
  route_stop_times?: Json;
  show_prospect_accounts?: boolean;
};

export type NbUsersRow = {
  id: string;
  name: string;
  hubspot_owner_id: string;
  owner_name: string;
  pin_salt: string;
  pin_hash: string;
  prefs_id: number;
  features: string[] | null;
  created_at: string;
  disabled_at: string | null;
};
export type NbUsersInsert = {
  id: string;
  name: string;
  hubspot_owner_id: string;
  owner_name: string;
  pin_salt: string;
  pin_hash: string;
  prefs_id: number;
  features?: string[] | null;
  created_at?: string;
  disabled_at?: string | null;
};

export type NbVAccountFirstTouchRow = {
  account_id: string | null;
  first_touch_at: string | null;
};

export type NbVAccountLeadStageRow = {
  account_id: string | null;
  touchpoints: number | null;
  last_revenue_on: string | null;
  lead_stage: string | null;
};

export type NbVAccountPotentialRow = {
  account_id: string | null;
  name: string | null;
  store_type: string | null;
  retail_mode: string | null;
  locations_count: number | null;
  lifetime_revenue: number | null;
  potential: number | null;
  potential_confidence: number | null;
  potential_inputs_known: number | null;
  potential_inputs_total: number | null;
  origin: NbDataOrigin | null;
  potential_label: string | null;
  potential_grade: string | null;
};

export type NbVAccountProductMixRow = {
  account_id: string | null;
  top_category_lifetime: string | null;
  top_category_lifetime_revenue: number | null;
  top_category_12m: string | null;
  top_category_12m_revenue: number | null;
};

export type NbVAccountScoresCurrentRow = {
  id: number | null;
  account_id: string | null;
  kind: NbScoreKind | null;
  value: number | null;
  confidence: number | null;
  inputs: Json | null;
  inputs_known: number | null;
  inputs_total: number | null;
  config_version: string | null;
  computed_at: string | null;
  computed_by: string | null;
  origin: NbDataOrigin | null;
  synthetic_dataset_id: string | null;
};

export type NbVAccountTierRow = {
  account_id: string | null;
  name: string | null;
  lifecycle: string | null;
  fit: number | null;
  fit_confidence: number | null;
  fit_inputs_known: number | null;
  fit_inputs_total: number | null;
  engagement: number | null;
  origin: NbDataOrigin | null;
  tier: string | null;
  area: string | null;
  hubspot_owner_id: string | null;
  chain_excluded: boolean | null;
  practice_excluded: boolean | null;
  closed_at: string | null;
};

export type NbVActivitiesEffectiveRow = {
  id: number | null;
  account_id: string | null;
  contact_id: string | null;
  at: string | null;
  logged_at: string | null;
  kind: NbActivityKind | null;
  direction: NbActivityDir | null;
  actor: string | null;
  outcome: string | null;
  detail: string | null;
  route_stop_id: string | null;
  hubspot_engagement_id: string | null;
  origin: NbDataOrigin | null;
  synthetic_dataset_id: string | null;
  effective_kind: NbActivityKind | null;
  corrected: boolean | null;
  correction_reason: string | null;
  retracted: boolean | null;
  retraction_reason: string | null;
  retracts_duplicate_of: number | null;
};

export type NbVCadenceDueRow = {
  account_id: string | null;
  name: string | null;
  tier: string | null;
  fit: number | null;
  fit_confidence: number | null;
  fit_inputs_known: number | null;
  fit_inputs_total: number | null;
  origin: NbDataOrigin | null;
  last_visit: string | null;
  last_email: string | null;
  last_call: string | null;
  last_inbound: string | null;
  in_person_days: number | null;
  email_days: number | null;
  call_days: number | null;
  never_visited: boolean | null;
  never_emailed: boolean | null;
  visit_days_overdue: number | null;
  email_days_overdue: number | null;
};

export type NbVFitMetricsRow = {
  account_id: string | null;
  fit: number | null;
  fit_confidence: number | null;
  inputs_known: number | null;
  inputs_total: number | null;
  core_known: boolean | null;
};

export type NbVKpiLeadingDailyRow = {
  day: string | null;
  origin: NbDataOrigin | null;
  visits: number | null;
  calls: number | null;
  texts: number | null;
  emails_out: number | null;
  linkedin_touches: number | null;
  samples_dropped: number | null;
  staff_trainings: number | null;
  meetings: number | null;
  replies_in: number | null;
  accounts_visited: number | null;
};

export type NbVKpiReactivationRow = {
  origin: NbDataOrigin | null;
  accounts_with_trial: number | null;
  accounts_reactivated: number | null;
  trial_to_reorder_pct: number | null;
  avg_days_trial_to_reorder: number | null;
};

export type NbVKpiRevenueMonthlyRow = {
  month: string | null;
  origin: NbDataOrigin | null;
  revenue: number | null;
  order_count: number | null;
  active_accounts: number | null;
  source_coverage_pct: number | null;
  by_source: Json | null;
};

export type NbVKpiVisitToCloseRow = {
  month: string | null;
  origin: NbDataOrigin | null;
  visits: number | null;
  orders_won: number | null;
  visit_to_close_pct: number | null;
};

export type NbVKpiVisitsPlannedVsDoneRow = {
  day: string | null;
  origin: NbDataOrigin | null;
  planned: number | null;
  completed: number | null;
  skipped: number | null;
  completion_pct: number | null;
};

export type NbVOriginCensusRow = {
  tbl: string | null;
  origin: string | null;
  count: number | null;
};

export type NbVPipelineStaleRow = {
  deal_id: string | null;
  account_id: string | null;
  account_name: string | null;
  stage: NbDealStage | null;
  next_step: string | null;
  next_step_date: string | null;
  next_step_days_overdue: number | null;
  last_activity_at: string | null;
  days_since_activity: number | null;
  tier: string | null;
  origin: NbDataOrigin | null;
};

export type NbVProspectingLaggedRow = {
  prospecting_month: string | null;
  origin: NbDataOrigin | null;
  prospecting_touches: number | null;
  revenue_month: string | null;
  revenue_90d_later: number | null;
};

export type NbVReportMetricsAlltimeRow = {
  metric: string | null;
  total: number | null;
  days: number | null;
  through_date: string | null;
  user_id: string | null;
};

export type NbVisitRecordingsRow = {
  id: string;
  account_id_hint: string | null;
  audio_path: string;
  status: string;
  transcript: string | null;
  touchpoint_id: string | null;
  error: string | null;
  started_at: string | null;
  ended_at: string | null;
  created_at: string;
};
export type NbVisitRecordingsInsert = {
  id?: string;
  account_id_hint?: string | null;
  audio_path: string;
  status?: string;
  transcript?: string | null;
  touchpoint_id?: string | null;
  error?: string | null;
  started_at?: string | null;
  ended_at?: string | null;
  created_at?: string;
};

export type Tables = {
  nb_account_briefs: { Row: NbAccountBriefsRow; Insert: NbAccountBriefsInsert };
  nb_account_events: { Row: NbAccountEventsRow; Insert: NbAccountEventsInsert };
  nb_account_scores: { Row: NbAccountScoresRow; Insert: NbAccountScoresInsert };
  nb_accounts: { Row: NbAccountsRow; Insert: NbAccountsInsert };
  nb_activities: { Row: NbActivitiesRow; Insert: NbActivitiesInsert };
  nb_activity_corrections: { Row: NbActivityCorrectionsRow; Insert: NbActivityCorrectionsInsert };
  nb_activity_retractions: { Row: NbActivityRetractionsRow; Insert: NbActivityRetractionsInsert };
  nb_app_errors: { Row: NbAppErrorsRow; Insert: NbAppErrorsInsert };
  nb_calendar_proposals: { Row: NbCalendarProposalsRow; Insert: NbCalendarProposalsInsert };
  nb_close_signals: { Row: NbCloseSignalsRow; Insert: NbCloseSignalsInsert };
  nb_config: { Row: NbConfigRow; Insert: NbConfigInsert };
  nb_contacts: { Row: NbContactsRow; Insert: NbContactsInsert };
  nb_content_flags: { Row: NbContentFlagsRow; Insert: NbContentFlagsInsert };
  nb_deal_stage_events: { Row: NbDealStageEventsRow; Insert: NbDealStageEventsInsert };
  nb_deals: { Row: NbDealsRow; Insert: NbDealsInsert };
  nb_devices: { Row: NbDevicesRow; Insert: NbDevicesInsert };
  nb_directives: { Row: NbDirectivesRow; Insert: NbDirectivesInsert };
  nb_email_poll_log: { Row: NbEmailPollLogRow; Insert: NbEmailPollLogInsert };
  nb_field_notes: { Row: NbFieldNotesRow; Insert: NbFieldNotesInsert };
  nb_hubspot_associations: { Row: NbHubspotAssociationsRow; Insert: NbHubspotAssociationsInsert };
  nb_hubspot_object_map: { Row: NbHubspotObjectMapRow; Insert: NbHubspotObjectMapInsert };
  nb_hubspot_sync_log: { Row: NbHubspotSyncLogRow; Insert: NbHubspotSyncLogInsert };
  nb_idempotency_keys: { Row: NbIdempotencyKeysRow; Insert: NbIdempotencyKeysInsert };
  nb_import_batches: { Row: NbImportBatchesRow; Insert: NbImportBatchesInsert };
  nb_import_rows: { Row: NbImportRowsRow; Insert: NbImportRowsInsert };
  nb_jobs: { Row: NbJobsRow; Insert: NbJobsInsert };
  nb_matrix_items: { Row: NbMatrixItemsRow; Insert: NbMatrixItemsInsert };
  nb_order_emails: { Row: NbOrderEmailsRow; Insert: NbOrderEmailsInsert };
  nb_order_lines: { Row: NbOrderLinesRow; Insert: NbOrderLinesInsert };
  nb_orders: { Row: NbOrdersRow; Insert: NbOrdersInsert };
  nb_outbound_drafts: { Row: NbOutboundDraftsRow; Insert: NbOutboundDraftsInsert };
  nb_pin_attempts: { Row: NbPinAttemptsRow; Insert: NbPinAttemptsInsert };
  nb_promo_codes: { Row: NbPromoCodesRow; Insert: NbPromoCodesInsert };
  nb_promo_orders: { Row: NbPromoOrdersRow; Insert: NbPromoOrdersInsert };
  nb_promo_products: { Row: NbPromoProductsRow; Insert: NbPromoProductsInsert };
  nb_promo_templates: { Row: NbPromoTemplatesRow; Insert: NbPromoTemplatesInsert };
  nb_report_drafts: { Row: NbReportDraftsRow; Insert: NbReportDraftsInsert };
  nb_report_metrics: { Row: NbReportMetricsRow; Insert: NbReportMetricsInsert };
  nb_route_days: { Row: NbRouteDaysRow; Insert: NbRouteDaysInsert };
  nb_route_plan_revisions: { Row: NbRoutePlanRevisionsRow; Insert: NbRoutePlanRevisionsInsert };
  nb_route_plans: { Row: NbRoutePlansRow; Insert: NbRoutePlansInsert };
  nb_route_stops: { Row: NbRouteStopsRow; Insert: NbRouteStopsInsert };
  nb_sample_drops: { Row: NbSampleDropsRow; Insert: NbSampleDropsInsert };
  nb_samples: { Row: NbSamplesRow; Insert: NbSamplesInsert };
  nb_score_config_proposals: { Row: NbScoreConfigProposalsRow; Insert: NbScoreConfigProposalsInsert };
  nb_score_configs: { Row: NbScoreConfigsRow; Insert: NbScoreConfigsInsert };
  nb_sdr_schedule: { Row: NbSdrScheduleRow; Insert: NbSdrScheduleInsert };
  nb_search_jobs: { Row: NbSearchJobsRow; Insert: NbSearchJobsInsert };
  nb_support_issues: { Row: NbSupportIssuesRow; Insert: NbSupportIssuesInsert };
  nb_sync_conflicts: { Row: NbSyncConflictsRow; Insert: NbSyncConflictsInsert };
  nb_synthetic_datasets: { Row: NbSyntheticDatasetsRow; Insert: NbSyntheticDatasetsInsert };
  nb_territory_areas: { Row: NbTerritoryAreasRow; Insert: NbTerritoryAreasInsert };
  nb_touchpoints: { Row: NbTouchpointsRow; Insert: NbTouchpointsInsert };
  nb_traffic_corridors: { Row: NbTrafficCorridorsRow; Insert: NbTrafficCorridorsInsert };
  nb_ui_prefs: { Row: NbUiPrefsRow; Insert: NbUiPrefsInsert };
  nb_users: { Row: NbUsersRow; Insert: NbUsersInsert };
  nb_visit_recordings: { Row: NbVisitRecordingsRow; Insert: NbVisitRecordingsInsert };
};

export type Views = {
  nb_v_account_first_touch: { Row: NbVAccountFirstTouchRow };
  nb_v_account_lead_stage: { Row: NbVAccountLeadStageRow };
  nb_v_account_potential: { Row: NbVAccountPotentialRow };
  nb_v_account_product_mix: { Row: NbVAccountProductMixRow };
  nb_v_account_scores_current: { Row: NbVAccountScoresCurrentRow };
  nb_v_account_tier: { Row: NbVAccountTierRow };
  nb_v_activities_effective: { Row: NbVActivitiesEffectiveRow };
  nb_v_cadence_due: { Row: NbVCadenceDueRow };
  nb_v_fit_metrics: { Row: NbVFitMetricsRow };
  nb_v_kpi_leading_daily: { Row: NbVKpiLeadingDailyRow };
  nb_v_kpi_reactivation: { Row: NbVKpiReactivationRow };
  nb_v_kpi_revenue_monthly: { Row: NbVKpiRevenueMonthlyRow };
  nb_v_kpi_visit_to_close: { Row: NbVKpiVisitToCloseRow };
  nb_v_kpi_visits_planned_vs_done: { Row: NbVKpiVisitsPlannedVsDoneRow };
  nb_v_origin_census: { Row: NbVOriginCensusRow };
  nb_v_pipeline_stale: { Row: NbVPipelineStaleRow };
  nb_v_prospecting_lagged: { Row: NbVProspectingLaggedRow };
  nb_v_report_metrics_alltime: { Row: NbVReportMetricsAlltimeRow };
};

/** The row shape of any nb_* table or view, by name. */
export type RowOf<N extends keyof Tables | keyof Views> =
  N extends keyof Tables ? Tables[N]["Row"] : N extends keyof Views ? Views[N]["Row"] : never;

/** A hand-written row type, checked against the table: it compiles only when
 *  every key it names is a real column, so a renamed or dropped column breaks
 *  the build instead of a request. */
export type Columns<R, Of> = Exclude<keyof R, keyof Of> extends never ? R : { unknown_columns: Exclude<keyof R, keyof Of> };
