// GENERATED by scripts/sync_search_config.mjs. Do not edit by hand.
// Sources: nutribiotic/config/territory_areas.json and price_list.json in the
// agency repo. Re-run the script after either changes.

export type TerritoryArea = { id: string; cities: string[]; anchors: [number, number][] };

export const TERRITORY_AREAS: TerritoryArea[] = [
  {
    "id": "san-diego",
    "cities": [
      "san diego",
      "la jolla",
      "la mesa",
      "el cajon",
      "chula vista",
      "coronado",
      "national city",
      "point loma",
      "pacific beach",
      "ocean beach",
      "santee",
      "lakeside",
      "spring valley",
      "lemon grove",
      "alpine",
      "poway",
      "rancho bernardo",
      "bonita",
      "imperial beach",
      "julian",
      "ramona",
      "borrego springs"
    ],
    "anchors": [
      [
        32.7157,
        -117.1611
      ],
      [
        32.8328,
        -117.2713
      ],
      [
        32.7948,
        -116.9625
      ],
      [
        32.6401,
        -117.0842
      ],
      [
        32.9628,
        -117.0359
      ]
    ]
  },
  {
    "id": "oceanside",
    "cities": [
      "oceanside",
      "carlsbad",
      "encinitas",
      "cardiff",
      "cardiff by the sea",
      "cardiff-by-the-sea",
      "del mar",
      "escondido",
      "san marcos",
      "vista",
      "fallbrook",
      "solana beach",
      "rancho santa fe",
      "valley center",
      "bonsall",
      "pauma valley"
    ],
    "anchors": [
      [
        33.1959,
        -117.3795
      ],
      [
        33.1581,
        -117.3506
      ],
      [
        33.037,
        -117.292
      ],
      [
        33.1192,
        -117.0864
      ],
      [
        33.3764,
        -117.2511
      ]
    ]
  },
  {
    "id": "orange-county",
    "cities": [
      "huntington beach",
      "santa ana",
      "costa mesa",
      "newport beach",
      "tustin",
      "orange",
      "garden grove",
      "corona del mar",
      "westminster",
      "fountain valley",
      "midway city",
      "irvine",
      "lake forest",
      "mission viejo",
      "laguna beach",
      "laguna hills",
      "laguna niguel",
      "laguna woods",
      "aliso viejo",
      "dana point",
      "san juan capistrano",
      "san clemente",
      "rancho santa margarita",
      "ladera ranch",
      "trabuco canyon",
      "coto de caza",
      "foothill ranch",
      "capistrano beach",
      "anaheim",
      "cypress",
      "la palma",
      "stanton",
      "los alamitos",
      "seal beach"
    ],
    "anchors": [
      [
        33.6595,
        -117.9988
      ],
      [
        33.7455,
        -117.8677
      ],
      [
        33.6189,
        -117.9298
      ],
      [
        33.6846,
        -117.8265
      ],
      [
        33.5427,
        -117.7854
      ],
      [
        33.427,
        -117.612
      ],
      [
        33.8366,
        -117.9143
      ]
    ]
  },
  {
    "id": "inland-empire",
    "cities": [
      "riverside",
      "corona",
      "eastvale",
      "norco",
      "jurupa valley",
      "mira loma",
      "moreno valley",
      "perris",
      "menifee",
      "murrieta",
      "temecula",
      "wildomar",
      "lake elsinore",
      "san jacinto",
      "hemet",
      "sun city",
      "winchester",
      "nuevo",
      "anza",
      "aguanga"
    ],
    "anchors": [
      [
        33.9533,
        -117.3962
      ],
      [
        33.8753,
        -117.5664
      ],
      [
        33.9311,
        -117.5487
      ],
      [
        33.4936,
        -117.1484
      ],
      [
        33.6971,
        -117.185
      ],
      [
        33.9425,
        -117.2297
      ]
    ]
  },
  {
    "id": "east-la",
    "cities": [
      "alhambra",
      "monterey park",
      "san gabriel",
      "rosemead",
      "temple city",
      "sierra madre",
      "arcadia",
      "monrovia",
      "duarte",
      "el monte",
      "south el monte",
      "east los angeles",
      "baldwin park",
      "irwindale",
      "azusa",
      "glendora",
      "san dimas",
      "la verne",
      "claremont",
      "covina",
      "west covina",
      "walnut",
      "diamond bar",
      "rowland heights",
      "hacienda heights",
      "la puente",
      "industry",
      "city of industry",
      "pomona",
      "downey",
      "norwalk",
      "cerritos",
      "artesia",
      "hawaiian gardens",
      "lakewood",
      "la mirada",
      "santa fe springs",
      "whittier",
      "pico rivera",
      "montebello",
      "commerce",
      "brea",
      "la habra",
      "buena park",
      "fullerton",
      "placentia",
      "yorba linda",
      "ontario",
      "upland",
      "montclair",
      "rancho cucamonga",
      "fontana",
      "rialto",
      "san bernardino",
      "colton",
      "loma linda",
      "redlands",
      "yucaipa",
      "highland",
      "grand terrace",
      "bloomington",
      "chino",
      "chino hills"
    ],
    "anchors": [
      [
        34.0954,
        -118.124
      ],
      [
        34.0625,
        -118.1228
      ],
      [
        34.1397,
        -118.0353
      ],
      [
        34.0686,
        -118.0276
      ],
      [
        34.0686,
        -117.939
      ],
      [
        34.1361,
        -117.8653
      ],
      [
        34.0286,
        -117.8103
      ],
      [
        34.0551,
        -117.75
      ],
      [
        33.9401,
        -118.1332
      ],
      [
        33.9022,
        -118.0817
      ],
      [
        33.8586,
        -118.0648
      ],
      [
        33.9163,
        -118.062
      ],
      [
        33.9792,
        -118.0328
      ],
      [
        33.9164,
        -117.9001
      ],
      [
        33.8703,
        -117.9243
      ],
      [
        34.0633,
        -117.6509
      ],
      [
        34.1064,
        -117.5931
      ],
      [
        34.1083,
        -117.2898
      ],
      [
        34.0556,
        -117.1825
      ]
    ]
  },
  {
    "id": "palm-desert",
    "cities": [
      "palm desert",
      "palm springs",
      "cathedral city",
      "rancho mirage",
      "la quinta",
      "indian wells",
      "indio",
      "desert hot springs",
      "coachella",
      "thousand palms",
      "bermuda dunes",
      "yucca valley",
      "joshua tree",
      "twentynine palms",
      "banning",
      "beaumont",
      "calimesa",
      "idyllwild",
      "blythe"
    ],
    "anchors": [
      [
        33.7222,
        -116.3744
      ],
      [
        33.8303,
        -116.5453
      ],
      [
        33.7206,
        -116.2156
      ],
      [
        34.1142,
        -116.4322
      ],
      [
        33.9256,
        -116.8767
      ]
    ]
  },
  {
    "id": "south-bay",
    "cities": [
      "el segundo",
      "hawthorne",
      "lawndale",
      "torrance",
      "west torrance",
      "palos verdes estates",
      "rancho palos verdes",
      "rolling hills estates",
      "rolling hills",
      "manhattan beach",
      "hermosa beach",
      "redondo beach"
    ],
    "anchors": [
      [
        33.8358,
        -118.3406
      ],
      [
        33.8847,
        -118.4109
      ],
      [
        33.8622,
        -118.3995
      ],
      [
        33.9192,
        -118.3517
      ],
      [
        33.7445,
        -118.387
      ],
      [
        33.7783,
        -118.4165
      ]
    ]
  },
  {
    "id": "south-la",
    "cities": [
      "gardena",
      "carson",
      "san pedro",
      "lomita",
      "harbor city",
      "wilmington",
      "inglewood",
      "compton",
      "westchester",
      "long beach",
      "signal hill",
      "paramount",
      "bellflower",
      "huntington park",
      "south gate",
      "lynwood",
      "bell",
      "bell gardens",
      "maywood",
      "vernon",
      "south los angeles",
      "exposition park",
      "university park",
      "west adams",
      "leimert park",
      "crenshaw",
      "watts",
      "florence",
      "walnut park",
      "willowbrook",
      "athens",
      "hyde park",
      "vermont square",
      "jefferson park",
      "adams-normandie",
      "historic south central"
    ],
    "anchors": [
      [
        33.7701,
        -118.1937
      ],
      [
        33.9164,
        -118.3526
      ],
      [
        33.7361,
        -118.2922
      ],
      [
        34.0224,
        -118.2851
      ],
      [
        34.0128,
        -118.335
      ],
      [
        33.9425,
        -118.2417
      ],
      [
        33.9617,
        -118.3531
      ],
      [
        33.9836,
        -118.22
      ],
      [
        33.8892,
        -118.1698
      ]
    ]
  },
  {
    "id": "santa-monica-venice",
    "cities": [
      "santa monica",
      "marina del rey",
      "venice",
      "playa vista",
      "playa del rey",
      "mar vista",
      "palms",
      "malibu",
      "pacific palisades"
    ],
    "anchors": [
      [
        34.0195,
        -118.4912
      ],
      [
        33.985,
        -118.4695
      ],
      [
        33.9802,
        -118.4517
      ],
      [
        33.96,
        -118.505
      ],
      [
        33.99,
        -118.505
      ],
      [
        34.02,
        -118.505
      ],
      [
        34.05,
        -118.505
      ],
      [
        34.08,
        -118.505
      ],
      [
        34.11,
        -118.505
      ],
      [
        34.0479,
        -118.5265
      ],
      [
        34.0259,
        -118.7798
      ]
    ]
  },
  {
    "id": "westwood",
    "cities": [
      "westwood",
      "brentwood",
      "sawtelle",
      "bel air",
      "century city",
      "west los angeles",
      "cheviot hills",
      "culver city"
    ],
    "anchors": [
      [
        34.0622,
        -118.4457
      ],
      [
        34.0576,
        -118.4162
      ],
      [
        33.96,
        -118.445
      ],
      [
        33.99,
        -118.445
      ],
      [
        34.02,
        -118.445
      ],
      [
        34.05,
        -118.445
      ],
      [
        34.08,
        -118.445
      ],
      [
        34.11,
        -118.445
      ],
      [
        34.0211,
        -118.3965
      ],
      [
        34.01,
        -118.4034
      ]
    ]
  },
  {
    "id": "beverly-hills-weho",
    "cities": [
      "beverly hills",
      "west hollywood"
    ],
    "anchors": [
      [
        34.0736,
        -118.4004
      ],
      [
        34.09,
        -118.3617
      ],
      [
        34.0837,
        -118.3853
      ],
      [
        34.0669,
        -118.38
      ]
    ]
  },
  {
    "id": "hollywood-pasadena",
    "cities": [
      "hollywood",
      "east hollywood",
      "los feliz",
      "silver lake",
      "echo park",
      "koreatown",
      "downtown los angeles",
      "boyle heights",
      "highland park",
      "eagle rock",
      "atwater village",
      "glendale",
      "burbank",
      "north hollywood",
      "toluca lake",
      "valley village",
      "tujunga",
      "sunland",
      "montrose",
      "la canada",
      "la canada flintridge",
      "altadena",
      "pasadena",
      "south pasadena",
      "san marino"
    ],
    "anchors": [
      [
        34.0928,
        -118.3287
      ],
      [
        34.0522,
        -118.2437
      ],
      [
        34.1425,
        -118.2551
      ],
      [
        34.1478,
        -118.1445
      ],
      [
        34.1808,
        -118.309
      ],
      [
        34.0619,
        -118.3005
      ],
      [
        34.1136,
        -118.1503
      ],
      [
        34.1206,
        -118.192
      ]
    ]
  },
  {
    "id": "woodland-hills",
    "cities": [
      "woodland hills",
      "tarzana",
      "encino",
      "sherman oaks",
      "studio city",
      "van nuys",
      "canoga park",
      "west hills",
      "winnetka",
      "reseda",
      "lake balboa",
      "topanga",
      "thousand oaks",
      "westlake village",
      "newbury park",
      "agoura hills",
      "agoura",
      "oak park",
      "calabasas"
    ],
    "anchors": [
      [
        34.1683,
        -118.6059
      ],
      [
        34.1516,
        -118.4494
      ],
      [
        34.1592,
        -118.5006
      ],
      [
        34.2011,
        -118.6031
      ],
      [
        34.1478,
        -118.3965
      ],
      [
        34.1706,
        -118.8376
      ],
      [
        34.1367,
        -118.6614
      ],
      [
        34.1467,
        -118.7615
      ]
    ]
  },
  {
    "id": "upper-valley",
    "cities": [
      "northridge",
      "granada hills",
      "porter ranch",
      "chatsworth",
      "north hills",
      "mission hills",
      "panorama city",
      "sun valley",
      "arleta",
      "pacoima",
      "sylmar",
      "san fernando",
      "shadow hills",
      "santa clarita",
      "newhall",
      "valencia",
      "stevenson ranch",
      "castaic",
      "canyon country",
      "saugus",
      "lancaster",
      "palmdale",
      "quartz hill",
      "littlerock",
      "acton",
      "rosamond",
      "simi valley",
      "santa rosa valley"
    ],
    "anchors": [
      [
        34.2281,
        -118.537
      ],
      [
        34.2819,
        -118.439
      ],
      [
        34.3917,
        -118.5426
      ],
      [
        34.2761,
        -118.567
      ],
      [
        34.6868,
        -118.1542
      ],
      [
        34.5794,
        -118.1165
      ],
      [
        34.2694,
        -118.7815
      ],
      [
        34.2264,
        -118.8853
      ]
    ]
  },
  {
    "id": "ventura",
    "cities": [
      "ventura",
      "san buenaventura",
      "oxnard",
      "port hueneme",
      "ojai",
      "santa paula",
      "fillmore",
      "piru",
      "camarillo",
      "somis",
      "moorpark"
    ],
    "anchors": [
      [
        34.2746,
        -119.229
      ],
      [
        34.1975,
        -119.1771
      ],
      [
        34.448,
        -119.2429
      ],
      [
        34.2164,
        -119.0376
      ]
    ]
  },
  {
    "id": "santa-barbara",
    "cities": [
      "santa barbara",
      "montecito",
      "goleta",
      "carpinteria",
      "isla vista",
      "summerland",
      "hope ranch",
      "mission canyon",
      "solvang",
      "santa ynez",
      "buellton",
      "ballard",
      "los olivos",
      "los alamos",
      "gaviota",
      "lompoc",
      "vandenberg"
    ],
    "anchors": [
      [
        34.4208,
        -119.6982
      ],
      [
        34.4358,
        -119.8276
      ],
      [
        34.42,
        -119.514
      ],
      [
        34.5958,
        -120.1376
      ],
      [
        34.6391,
        -120.4579
      ]
    ]
  },
  {
    "id": "san-luis-obispo",
    "cities": [
      "san luis obispo",
      "paso robles",
      "el paso de robles",
      "pismo beach",
      "pismo",
      "arroyo grande",
      "grover beach",
      "santa maria",
      "orcutt",
      "guadalupe",
      "atascadero",
      "morro bay",
      "nipomo",
      "los osos",
      "cambria",
      "templeton",
      "san miguel",
      "shell beach",
      "avila beach",
      "oceano",
      "cayucos",
      "san simeon",
      "creston",
      "santa margarita"
    ],
    "anchors": [
      [
        35.2828,
        -120.6596
      ],
      [
        35.6266,
        -120.691
      ],
      [
        35.1428,
        -120.6413
      ],
      [
        34.953,
        -120.4357
      ],
      [
        35.3659,
        -120.8499
      ]
    ]
  },
  {
    "id": "inland",
    "cities": [
      "bakersfield",
      "mojave",
      "california city",
      "boron",
      "tehachapi",
      "victorville",
      "apple valley",
      "yucca loma",
      "hesperia",
      "adelanto",
      "phelan",
      "barstow",
      "delano",
      "mcfarland",
      "wasco",
      "shafter",
      "buttonwillow",
      "taft",
      "arvin",
      "lake isabella",
      "kernville",
      "ridgecrest",
      "frazier park",
      "lebec"
    ],
    "anchors": []
  }
];

export const AMBIGUOUS_CITIES: string[] = ["los angeles"];

export const CATALOG_TERMS: string[] = [
  "amla vitamin c",
  "ascorbate bio-c",
  "ascorbic acid",
  "ascorbic acid with bioflavonoids",
  "body & foot powder",
  "body crème",
  "bubble bath",
  "buffered vitamin c",
  "calcium ascorbate",
  "calcium magnesium",
  "chlorella",
  "clarity+focus & memory",
  "defenseplus",
  "dental gel",
  "dental gel plus",
  "deodorant",
  "dual relax",
  "ear drops",
  "electro-c",
  "electro-c cherry",
  "electro-c lemon",
  "essential electrolytes",
  "everyday clean conditioner",
  "everyday clean shampoo",
  "everyday nourish conditioner",
  "everyday nourish shampoo",
  "everyday pure conditioner",
  "everyday pure shampoo",
  "everyday volume conditioner",
  "everyday volume shampoo",
  "face crème",
  "foaming facial cleanser",
  "grapefruit seed extract",
  "gse capsules",
  "gse capsulesplus",
  "gse tablets",
  "hand & body lotion",
  "hydrating facial toner",
  "hypo-aller c",
  "maximum gse liquid con.",
  "meta-c",
  "metarest capsules",
  "mouthfresh",
  "multi mineral",
  "multi vitamins & minerals",
  "nasal spray",
  "nasal spray plus",
  "oral care",
  "organic rice protein",
  "pea protein",
  "peptide face crème",
  "pure coconut oil soap",
  "rice protein",
  "sensitive skin cleanser",
  "skin & wound spray",
  "skin cleanser",
  "skin ointment",
  "skin serum",
  "sodium ascorbate",
  "sodium ascorbate capsules",
  "super shower gel",
  "supplement",
  "vitamin",
  "vitamin c (ascorbic acid)",
  "vitamin c + d3 & zinc"
];
