/**
 * The Workflow screen's starting documents: the NutriBiotic marketing content
 * pipeline (every output assembled only from pre-approved claims, checked
 * again before it goes out) and the Marketing Drive it reads from and writes
 * to. Transcribed from the plan as written; nothing here is a new fact.
 */

import { newId, type Folder, type FolderTree, type Step, type WorkflowMap } from "./types";

export const SEED_MAP: WorkflowMap = {
  title: "Marketing content pipeline",
  summary: "Every output is assembled only from pre-approved claims, then checked again before it is published.",
  phases: [
    { id: "src", name: "Source" },
    { id: "clm", name: "Claims" },
    { id: "plan", name: "Plan" },
    { id: "cre", name: "Create" },
    { id: "cmp", name: "Comply" },
    { id: "ren", name: "Render" },
    { id: "pub", name: "Publish" },
    { id: "mon", name: "Monitor" },
  ],
  steps: [
    {
      id: "src_01_intake",
      name: "Collect source material",
      phase: "src",
      actorNow: "Human",
      actorTarget: "System",
      typology: "Deterministic",
      input: "Spec sheets, COAs, studies (.pdf, .docx) in a Drive folder",
      output: "File record (.json)",
      filter: "F1",
      tool: "n8n Drive trigger",
    },
    {
      id: "src_02_extract",
      name: "Pull facts and candidate claims from studies and specs",
      phase: "src",
      actorNow: "Human",
      actorTarget: "Agent",
      typology: "Extraction",
      input: "Study or spec (.pdf)",
      output: "Candidate claims with dose, form, population (.json)",
      filter: "F2",
      tool: "Extraction agent",
    },
    {
      id: "clm_03_evidence",
      name: "Grade evidence against the FTC standard",
      phase: "clm",
      actorNow: "Human",
      actorTarget: "Agent proposes",
      typology: "Cognitive: evaluation",
      input: "Candidate claims (.json) + full studies",
      output: "Evidence memo with gaps (.md)",
      filter: "F3",
      tool: "Human gate",
    },
    {
      id: "clm_04_approve",
      name: "Approve claim into the library",
      phase: "clm",
      actorNow: "Human",
      actorTarget: "Human stays",
      typology: "High-stakes approval",
      input: "Evidence memo (.md)",
      output: "Claims Library row (Supabase)",
      filter: "F3",
      tool: "Human gate",
      note: "Agents never write to the Claims Library. A new claim only enters here.",
    },
    {
      id: "clm_05_notify",
      name: "Track 30-day FDA notification for label claims",
      phase: "clm",
      actorNow: "Human",
      actorTarget: "System",
      typology: "Deterministic",
      input: "New label claim row",
      output: "Task + notified date",
      filter: "F1",
      tool: "n8n schedule",
    },
    {
      id: "plan_06_calendar",
      name: "Build the content calendar",
      phase: "plan",
      actorNow: "Human",
      actorTarget: "Agent proposes",
      typology: "Cognitive: synthesis",
      input: "Launch roadmap, seasonality, last month's metrics (.csv)",
      output: "Calendar items (.json)",
      filter: "F3",
      tool: "Light human approval",
    },
    {
      id: "plan_07_brief",
      name: "Write a brief per piece",
      phase: "plan",
      actorNow: "Human",
      actorTarget: "Agent",
      typology: "Cognitive: low risk",
      input: "Calendar item (.json) + allowed claim_ids",
      output: "Brief: audience, channel set, claim_ids (.json)",
      filter: "AUTO",
      tool: "Autonomous agent",
    },
    {
      id: "cre_08_master",
      name: "Draft channel-neutral content blocks",
      phase: "cre",
      actorNow: "Human",
      actorTarget: "Agent",
      typology: "Cognitive: creative",
      input: "Brief (.json) + claim rows",
      output: "Content blocks, each claim tagged by claim_id (.json)",
      filter: "AUTO",
      tool: "Autonomous agent, gated downstream",
    },
    {
      id: "cre_09_visuals",
      name: "Produce imagery and layouts",
      phase: "cre",
      actorNow: "Human",
      actorTarget: "Agent + Canva",
      typology: "Cognitive: creative",
      input: "Brief + brand kit",
      output: "Image assets (.png)",
      filter: "AUTO",
      tool: "Autonomous agent, gated downstream",
    },
    {
      id: "cmp_10_lint",
      name: "Rule check: every claim maps to an approved claim_id; banned terms; disclaimers present",
      phase: "cmp",
      actorNow: "Human",
      actorTarget: "System",
      typology: "Deterministic",
      input: "Content blocks (.json)",
      output: "Lint report (.json)",
      filter: "F1",
      tool: "n8n code node",
    },
    {
      id: "cmp_11_review",
      name: "AI compliance review: net impression, implied claims, images, qualifiers",
      phase: "cmp",
      actorNow: "Human",
      actorTarget: "Agent",
      typology: "Cognitive: evaluation",
      input: "Blocks (.json) + images",
      output: "Risk report: score, flagged spans, rule cited (.json)",
      filter: "AUTO",
      tool: "Autonomous agent, routes to gate",
    },
    {
      id: "cmp_12_signoff",
      name: "Compliance sign-off",
      phase: "cmp",
      actorNow: "Human",
      actorTarget: "Human stays",
      typology: "High-stakes approval",
      input: "Draft + risk report",
      output: "Approval record with name and timestamp (.json)",
      filter: "F3",
      tool: "Human gate",
      note: "A piece is final only when this step writes an approval record (asset ID, version hash, approver, timestamp). That record is the one signal n8n accepts to publish or send to print.",
    },
    {
      id: "ren_13_web",
      name: "Render to website page",
      phase: "ren",
      actorNow: "Human",
      actorTarget: "System",
      typology: "Deterministic",
      input: "Approved blocks (.json)",
      output: "CMS page via API",
      filter: "F1",
      tool: "n8n node",
    },
    {
      id: "ren_14_email",
      name: "Render and schedule newsletter",
      phase: "ren",
      actorNow: "Human",
      actorTarget: "System",
      typology: "Deterministic",
      input: "Approved blocks (.json)",
      output: "ESP campaign draft",
      filter: "F1",
      tool: "n8n node",
    },
    {
      id: "ren_15_consumer",
      name: "Render consumer handout",
      phase: "ren",
      actorNow: "Human",
      actorTarget: "System",
      typology: "Deterministic",
      input: "Approved blocks + Canva brand template",
      output: "Print-ready PDF",
      filter: "F1",
      tool: "Canva autofill",
    },
    {
      id: "ren_16_b2b",
      name: "Render B2B sell sheet with wholesale terms",
      phase: "ren",
      actorNow: "Human",
      actorTarget: "System",
      typology: "Deterministic",
      input: "Approved blocks + price list (.csv)",
      output: "Print-ready PDF",
      filter: "F1",
      tool: "Canva autofill",
    },
    {
      id: "pub_17_proof",
      name: "Re-review the rendered output",
      phase: "pub",
      actorNow: "Human",
      actorTarget: "Agent",
      typology: "Extraction + evaluation",
      input: "Rendered PDF or page",
      output: "Pass, or diff against approved version (.json)",
      filter: "F2",
      tool: "Extraction agent",
      note: "Layout and imagery change an ad's net impression, so the rendered artifact gets checked, not just the text that went into it.",
    },
    {
      id: "pub_18_archive",
      name: "Archive final, approval and evidence snapshot",
      phase: "pub",
      actorNow: "Human",
      actorTarget: "System",
      typology: "Deterministic",
      input: "Final asset + approval record",
      output: "Audit bundle in Drive + Supabase",
      filter: "F1",
      tool: "n8n node",
    },
    {
      id: "mon_19_watch",
      name: "Watch reviews, social, Amazon and retailer pages for off-label claims",
      phase: "mon",
      actorNow: "Human",
      actorTarget: "Agent",
      typology: "Extraction",
      input: "Scraped text",
      output: "Flagged items (.json)",
      filter: "F2",
      tool: "Extraction agent",
    },
    {
      id: "mon_20_report",
      name: "Weekly performance report",
      phase: "mon",
      actorNow: "Human",
      actorTarget: "Agent",
      typology: "Cognitive: synthesis",
      input: "Analytics exports (.csv)",
      output: "Report (.md) feeding plan_06",
      filter: "AUTO",
      tool: "Autonomous agent",
    },
  ] satisfies Step[],
};

const folder = (name: string, purpose?: string, steps?: string[], children: Folder[] = []): Folder => ({
  id: newId(),
  name,
  ...(purpose ? { purpose } : {}),
  ...(steps ? { steps } : {}),
  children,
});

export const SEED_TREE: FolderTree = {
  title: "Marketing Drive",
  root: folder("Marketing", undefined, undefined, [
    folder(
      "01 Intake",
      "Specs, COAs and studies as they arrive; n8n watches this folder",
      ["src_01_intake", "src_02_extract"],
      [folder("Spec sheets"), folder("COAs"), folder("Studies")],
    ),
    folder(
      "02 Claims",
      "Evidence memos and the studies behind each approved claim",
      ["clm_03_evidence", "clm_04_approve", "clm_05_notify"],
      [folder("Evidence memos"), folder("FDA notifications")],
    ),
    folder(
      "03 Plan",
      "Content calendar exports and briefs",
      ["plan_06_calendar", "plan_07_brief"],
      [folder("Calendar"), folder("Briefs")],
    ),
    folder(
      "04 Drafts",
      "Channel-neutral content blocks and image assets before review",
      ["cre_08_master", "cre_09_visuals"],
      [folder("Content blocks"), folder("Images")],
    ),
    folder(
      "05 Compliance",
      "Lint reports, risk reports and approval records",
      ["cmp_10_lint", "cmp_11_review", "cmp_12_signoff"],
      [folder("Lint reports"), folder("Risk reports"), folder("Approvals")],
    ),
    folder(
      "06 Rendered",
      "Final outputs per channel",
      ["ren_13_web", "ren_14_email", "ren_15_consumer", "ren_16_b2b", "pub_17_proof"],
      [folder("Website"), folder("Newsletter"), folder("Consumer handouts"), folder("B2B sell sheets")],
    ),
    folder("07 Archive", "Audit bundles: final asset, approval record, evidence snapshot", ["pub_18_archive"]),
    folder(
      "08 Monitoring",
      "Flagged off-label mentions and weekly reports",
      ["mon_19_watch", "mon_20_report"],
      [folder("Flags"), folder("Weekly reports")],
    ),
    folder("Brand kit", "Canva templates, logos, price list", ["cre_09_visuals", "ren_15_consumer", "ren_16_b2b"]),
    folder("Current copy", "Today's website copy and handouts, the compliance engine's first test set", [
      "cmp_10_lint",
      "cmp_11_review",
    ]),
  ]),
};
