#!/usr/bin/env python3
"""Write src/lib/db/types.ts: one Row type per nb_* table and view, an Insert
type per table, and every nb_* enum, read from the production catalog. Same
read-only path and token as scripts/dump_schema.py.

  python3 scripts/gen_db_types.py            # rewrite src/lib/db/types.ts
  python3 scripts/gen_db_types.py --check    # exit 1 if production drifted
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from dump_schema import PREFIX, REF, q  # noqa: E402

OUT = Path(__file__).resolve().parents[1] / "src" / "lib" / "db" / "types.ts"

SCALAR = {
    "text": "string", "character varying": "string", "character": "string", "uuid": "string",
    "date": "string", "timestamp with time zone": "string", "timestamp without time zone": "string",
    "time without time zone": "string", "interval": "string", "citext": "string", "inet": "string",
    "bytea": "string", "tsvector": "string",
    "smallint": "number", "integer": "number", "bigint": "number", "real": "number",
    "double precision": "number", "numeric": "number",
    "boolean": "boolean", "json": "Json", "jsonb": "Json",
}


def pascal(name: str) -> str:
    return "".join(p.capitalize() for p in name.split("_"))


def ts_type(typ: str, enums: set[str]) -> str:
    arr = typ.endswith("[]")
    base = typ[:-2] if arr else typ
    base = base.split("(")[0].strip()
    t = pascal(base) if base in enums else SCALAR.get(base, "unknown")
    return f"{t}[]" if arr else t


def build() -> str:
    enums = q(f"""
        select t.typname, json_agg(e.enumlabel order by e.enumsortorder) labels
        from pg_type t join pg_namespace n on n.oid=t.typnamespace join pg_enum e on e.enumtypid=t.oid
        where n.nspname='public' and t.typname like '{PREFIX}' group by 1 order by 1""")
    enum_names = {e["typname"] for e in enums}
    cols = q(f"""
        select c.relname, c.relkind::text kind, a.attname, format_type(a.atttypid, a.atttypmod) typ,
               a.attnotnull nn, (a.atthasdef or a.attidentity <> '' ) has_def, a.attgenerated <> '' gen
        from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace
        where n.nspname='public' and c.relkind in ('r','p','v') and c.relname like '{PREFIX}'
          and a.attnum>0 and not a.attisdropped order by c.relname, a.attnum""")

    out = [
        "// Generated by scripts/gen_db_types.py from the production catalog",
        f"// (project {REF}). Do not edit by hand; rerun the script after a migration.",
        "",
        "export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];",
        "",
    ]
    for e in enums:
        out.append(f"export type {pascal(e['typname'])} = " + " | ".join(f'"{x}"' for x in e["labels"]) + ";")
    out.append("")

    rels: dict[str, list[dict]] = {}
    for c in cols:
        rels.setdefault(c["relname"], []).append(c)
    tables, views = [], []
    for name, cs in rels.items():
        is_view = cs[0]["kind"] == "v"
        row = [f"  {c['attname']}: {ts_type(c['typ'], enum_names)}"
               + ("" if c["nn"] and not is_view else " | null") + ";" for c in cs]
        out.append(f"export type {pascal(name)}Row = {{\n" + "\n".join(row) + "\n};")
        if is_view:
            views.append(name)
        else:
            tables.append(name)
            ins = [f"  {c['attname']}{'' if c['nn'] and not c['has_def'] else '?'}: "
                   f"{ts_type(c['typ'], enum_names)}{'' if c['nn'] else ' | null'};"
                   for c in cs if not c["gen"]]
            out.append(f"export type {pascal(name)}Insert = {{\n" + "\n".join(ins) + "\n};")
        out.append("")

    out.append("export type Tables = {")
    out += [f"  {t}: {{ Row: {pascal(t)}Row; Insert: {pascal(t)}Insert }};" for t in tables]
    out.append("};")
    out.append("")
    out.append("export type Views = {")
    out += [f"  {v}: {{ Row: {pascal(v)}Row }};" for v in views]
    out.append("};")
    out.append("")
    out.append("/** The row shape of any nb_* table or view, by name. */")
    out.append("export type RowOf<N extends keyof Tables | keyof Views> =")
    out.append("  N extends keyof Tables ? Tables[N][\"Row\"] : N extends keyof Views ? Views[N][\"Row\"] : never;")
    out += [
        "",
        "/** A hand-written row type, checked against the table: it compiles only when",
        " *  every key it names is a real column, so a renamed or dropped column breaks",
        " *  the build instead of a request. */",
        "export type Columns<R, Of> = Exclude<keyof R, keyof Of> extends never ? R : { unknown_columns: Exclude<keyof R, keyof Of> };",
    ]
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    ts = build()
    if a.check:
        same = OUT.exists() and OUT.read_text() == ts
        print("no drift" if same else f"production differs from {OUT}")
        return 0 if same else 1
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(ts)
    print(f"wrote {OUT} ({len(ts.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
