#!/usr/bin/env node
// Regenerates src/lib/features/search/config.generated.ts from the agency's
// own config (nutribiotic/config/territory_areas.json and price_list.json).
// Vercel cannot see the agency repo, so the search pipeline needs these baked
// in; this script is the only writer of that file. Run it after either source
// changes:  node scripts/sync_search_config.mjs
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const app = path.resolve(here, "..");
const cfgDir = path.resolve(app, "..", "..", "nutribiotic", "config");
const out = path.join(app, "src", "lib", "features", "search", "config.generated.ts");

const territory = JSON.parse(readFileSync(path.join(cfgDir, "territory_areas.json"), "utf8"));
const priceList = JSON.parse(readFileSync(path.join(cfgDir, "price_list.json"), "utf8"));

const areas = territory.areas.map((a) => ({
  id: a.id,
  cities: a.cities ?? [],
  anchors: (a.anchors ?? []).map((p) => [Number(p[0]), Number(p[1])]),
}));

// Same derivation as places_search_ingest.catalog_terms(): the product head
// of each SKU name (before the comma), 5+ chars, plus the two shelf words.
const skus = priceList.skus ?? {};
if (!Object.keys(skus).length) throw new Error("price_list.json has no skus");
const terms = new Set(["supplement", "vitamin"]);
for (const s of Object.values(skus)) {
  const head = String(s.name ?? "").toLowerCase().split(",")[0].trim();
  if (head.length >= 5) terms.add(head);
}
const catalogTerms = [...terms].sort((x, y) => (x < y ? -1 : x > y ? 1 : 0));

const body = `// GENERATED by scripts/sync_search_config.mjs. Do not edit by hand.
// Sources: nutribiotic/config/territory_areas.json and price_list.json in the
// agency repo. Re-run the script after either changes.

export type TerritoryArea = { id: string; cities: string[]; anchors: [number, number][] };

export const TERRITORY_AREAS: TerritoryArea[] = ${JSON.stringify(areas, null, 2)};

export const AMBIGUOUS_CITIES: string[] = ${JSON.stringify(territory.ambiguous_cities ?? [])};

export const CATALOG_TERMS: string[] = ${JSON.stringify(catalogTerms, null, 2)};
`;
writeFileSync(out, body);
console.log(`wrote ${path.relative(app, out)}: ${areas.length} areas, ${catalogTerms.length} catalog terms`);
